export const GET_ALL_USERS = 'GET_ALL_USERS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const REMOVE_USER_INITIATE = 'REMOVE_USER_INITIATE';
export const REMOVE_USER = 'REMOVE_USER';
export const EDIT_USER_INFO = 'EDIT_USER_INFO';
export const EDIT_USER_INFO_INITIATE = 'EDIT_USER_INFO_INITIATE';


export const GET_ALL_USERS_INITIATE = 'GET_ALL_USERS_INITIATE'; 


export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const POPUP_CLOSE = 'POPUP_CLOSE';



